version: "3.8"

services:

  postgresql:
    image: postgres:17
    container_name: cashcard-postgresql
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_DB=cashcarddb
      - POSTGRES_USER=cashcard
      - POSTGRES_PASSWORD=cashcard
    volumes:
      - postgresql-data:/var/lib/postgresql/data

volumes:
  postgresql-data:
    name: cashcard-postgresql-data